// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sneakers_shop.Models;

#nullable disable

namespace Sneakersshop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221203220412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Sneakers_shop.Models.Admin_Model", b =>
                {
                    b.Property<int>("Ad_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad_Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad_Surename")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Ad_Id");

                    b.ToTable("admin_Models");

                    b.HasData(
                        new
                        {
                            AdId = 1,
                            AdPassword = "admin123",
                            AdSurename = "root"
                        },
                        new
                        {
                            AdId = 2,
                            AdPassword = "admin123",
                            AdSurename = "admin"
                        },
                        new
                        {
                            AdId = 3,
                            AdPassword = "admin123",
                            AdSurename = "test"
                        });
                });

            modelBuilder.Entity("Sneakers_shop.Models.Category_Model", b =>
                {
                    b.Property<int>("Catg_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Admin_FK_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Catg_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Catg_Id");

                    b.HasIndex("Admin_FK_Id");

                    b.ToTable("category_Models");
                });

            modelBuilder.Entity("Sneakers_shop.Models.ProdukcjaButow_Model", b =>
                {
                    b.Property<int>("Prod_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category_FK_Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Prod_Cena")
                        .HasColumnType("REAL");

                    b.Property<string>("Prod_Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prod_Kolor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prod_Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prod_Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Prod_Rodzaj")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_FK_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Prod_Id");

                    b.HasIndex("Category_FK_Id");

                    b.HasIndex("User_FK_Id");

                    b.ToTable("produkcjaButow_Models");
                });

            modelBuilder.Entity("Sneakers_shop.Models.User_Model", b =>
                {
                    b.Property<int>("U_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("U_Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("U_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("U_Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("U_Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("U_Id");

                    b.ToTable("user_Models");
                });

            modelBuilder.Entity("Sneakers_shop.Models.Category_Model", b =>
                {
                    b.HasOne("Sneakers_shop.Models.Admin_Model", "Admin_Model")
                        .WithMany("category_Models")
                        .HasForeignKey("Admin_FK_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin_Model");
                });

            modelBuilder.Entity("Sneakers_shop.Models.ProdukcjaButow_Model", b =>
                {
                    b.HasOne("Sneakers_shop.Models.Category_Model", "Category_Model")
                        .WithMany("produkcjaButow_Models")
                        .HasForeignKey("Category_FK_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sneakers_shop.Models.User_Model", "User_Model")
                        .WithMany("produkcjaButow_Models")
                        .HasForeignKey("User_FK_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category_Model");

                    b.Navigation("User_Model");
                });

            modelBuilder.Entity("Sneakers_shop.Models.Admin_Model", b =>
                {
                    b.Navigation("category_Models");
                });

            modelBuilder.Entity("Sneakers_shop.Models.Category_Model", b =>
                {
                    b.Navigation("produkcjaButow_Models");
                });

            modelBuilder.Entity("Sneakers_shop.Models.User_Model", b =>
                {
                    b.Navigation("produkcjaButow_Models");
                });
#pragma warning restore 612, 618
        }
    }
}
