// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sneakers_shop.Models;

#nullable disable

namespace Sneakersshop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221220182324_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Sneakers_shop.Models.ProdukcjaButow_Model", b =>
                {
                    b.Property<int>("Prod_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Prod_Cena")
                        .HasColumnType("REAL")
                        .HasColumnName("Cena butów");

                    b.Property<int>("Prod_Kolor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Kolor butów");

                    b.Property<string>("Prod_Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Marka butów");

                    b.Property<string>("Prod_Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Model butów");

                    b.Property<int>("Prod_Rodzaj")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Rodzaj butów");

                    b.HasKey("Prod_Id");

                    b.ToTable("Produkcja butów");
                });
#pragma warning restore 612, 618
        }
    }
}
